name: Deploy
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix for Nix caching
        uses: cachix/cachix-action@v10
        with:
          name: "${{ secrets.CACHIX_CACHE }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build TODOs service Docker container
        run: |
          nix build ".#docker"
          nix path-info --recursive | cachix push ${{ secrets.CACHIX_CACHE }}
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_ACCESS_TOKEN }}"
      - name: Load and push image
        run: |
          export IMAGE_TAG=$(docker load < result | grep -Po 'Loaded image: \K.*')
          docker push "${IMAGE_TAG}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
      - name: Deploy new image to Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment.apps/todos-deployment todos="${{ env.IMAGE_TAG }}"
      - name: Restart Kubernetes Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment.apps/todos-deployment
