# Borrowed from here: https://github.com/nix-dot-dev/getting-started-nix-template
name: Update Nix flake every day

on:
  schedule:
    # every day at 8am UTC
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Set up Cachix for Nix caching
        uses: cachix/cachix-action@v10
        with:
          name: "${{ secrets.CACHIX_CACHE }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Update the flake
        run: nix flake update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.0
        with:
          commit-message: "[automated] nix flake update"
          title: "[automated] Update Nix flake"
          branch: "ci/nix-flake-update"
